arrowParens: 'always'
printWidth: 150
singleQuote: true
tabWidth: 4
trailingComma: 'es5'
useTabs: false
bracketSpacing: true
endOfLine: 'auto'
htmlWhitespaceSensitivity: 'css'
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
proseWrap: 'preserve'
quoteProps: 'as-needed'
requirePragma: false
semi: true
vueIndentScriptAndStyle: false 